#!/bin/sh /etc/rc.common

USE_PROCD=1
START=99
STOP=01

start_service() {
	procd_open_instance
	procd_set_param command /usr/sbin/r3mini-fanctl
	procd_set_param respawn 3600 5 5
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

reload_service() {
	/etc/init.d/r3mini-fan restart
}

service_triggers() {
	procd_add_reload_trigger r3mini_fan
}
