#!/bin/sh /etc/rc.common

USE_PROCD=1
START=95
STOP=05

start_service() {
	procd_open_instance
	procd_set_param command /usr/sbin/r3mini-hotspot-watchdog
	procd_set_param respawn 3600 5 5
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

reload_service() {
	/etc/init.d/r3mini-hotspot restart
}

service_triggers() {
	procd_add_reload_trigger r3mini_hotspot wireless network
}
